### ISSUE TITLE
UDP receiver deadlock when running dual-port UDP example

### ISSUE THREAD

**Issue by hecmay** [OCT-FPGA/udp-network-demo#1]
Hi, 

I am trying to run the dual-port UDP encrypt/decrypt example on OCT Mass Cluster. I successfully compiled the bitstream on the build server and copied the files to FPGA nodes on the cloud. 

I ran the receiver and sender on pc155 and pc158 respectively. Here is the command I used  

```bash
# pc155
./host_receiver_if3 demo_if3.xclbin 1 1 decrypt decrypt

# pc158
./host_sender_if3 demo_if3.xclbin 1 1 encrypt encrypt
```

My problem is that the receiver is only able to receive packets on the first port, and then it is deadlocked, waiting for kernel 1 to be finished forever. Here is the output from the receiver side

```bash
# .... decrypted text received from port 0...
before seen a rabbit with either 
Device 0: Message received.
Enqueue user kernel 1...
```
I tried to swap the sender and receiver but still got into the same deadlock issue.
Not sure what the issue is. Can anyone please help?

**Comment by hecmay** [comment]
@surangamh do you have any clue?  or any tips on how to debug. Appreciate your help

**Comment by surangamh** [comment]
@hecmay I will investigate this. In the meantime, can you use the branch "2020.1" of this example? Build it and see if you run into the same issue. The VM has both 2020.2 and 2021.2 versions of Vitis. You should be able to use either of these to build.

**Comment by hecmay** [comment]
@surangamh thanks for your reply. 
Sure I will try the 2020.1 branch, and I will also try using both versions of Vitis to compile.

**Comment by surangamh** [comment]
@hecmay Branch 2020.1 should work. Be sure to select the tool version 2020.1.1 when you set up the CloudLab experiment. Other tool versions may not work.

**Comment by hecmay** [comment]
@surangamh thanks! I will try it today. may I know which v++ version did you use for compilation?

**Comment by surangamh** [comment]
@hecmay I have used 2020.1. However, this version of Vitis is not installed on the VM. You may try using 2020.2. In case your compilation fails, I will install 2020.1 on the VM.

**Comment by hecmay** [comment]
Sure. thanks! I am compiling with 2020.2 now. Will see if it works

**Comment by surangamh** [comment]
@hecmay Fixed.
